googleapis/java-spanner-jdbc

.repo-metadata.json
=> chore: fix distribution_name in .repo-metadata

pom.xml
Updates to latest libraries-bom and remove all exclusions that are no longer needed.
=> deps: upgrade to latest bom and remove dependency exclusions

.github/CODEOWNERS, .repo-metadata.json
Adds @googleapis/api-spanner-java as github codeowners.
=> build: adds api-spanner-java team as owners

.repo-metadata.json
=> docs: fix product docs link

.readme-partials.yaml
=> docs: add reference to jar-with-dependencies in readme

.github/blunderbuss.yml, synth.py
=> chore: add default assignee for issues

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcQueryOptionsTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcConnectTest.java
Add tests for rpcPriority
Fixes #656
=> tests: add tests for rpcPriority

.kokoro/nightly/integration.cfg, pom.xml
=> chore: correct Spanner instance reference for ITs

pom.xml
Reducing fork count to 4 to check if that helps reduce the flakes.
=> chore: reduce fork count to 4

.github/blunderbuss.yml
=> chore: change repo maintainer

pom.xml
I'm acting as the RenovateBot.
=> deps: google-cloud-spanner-bom 6.25.5

pom.xml
Related to https://github.com/googleapis/java-spanner-jdbc/issues/910
=> fix: pr to troubleshoot native image tests

pom.xml
RenovateBot didn't create a pull request. So I'm creating one by myself.
=> deps: google-cloud-spanner-bom 6.30.0

src/test/java/com/google/cloud/spanner/jdbc/SavepointMockServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/TagMockServerTest.java
Adds a couple of tests for statement and transaction tags.
=> test: add tag tests

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Enables the client-side statement cache.
=> chore: enable client-side statement cache

.github/workflows/unmanaged_dependency_check.yaml
=> chore: update version of unmanaged dependency check

src/test/java/com/google/cloud/spanner/jdbc/JdbcTransactionOptionsTest.java
Support added for `set max_commit_delay=<duration>` statement. Setting a max_commit_delay can increase throughput of bulk updates, as Spanner can batch more updates together, but at the expense of higher latency for a single request.
=> feat: support max_commit_delay

src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
Adds a verification to an existing test that the standard Java client lib header is included by the JDBC driver.
=> test: add test to verify client-lib header is included

src/test/java/com/google/cloud/spanner/jdbc/DdlMockServerTest.java
The JDBC driver should now support executing DDL using the executeUpdate methods of java.sql.Statement and
java.sql.PreparedStatement.
Closes #1150
=> test: verify that executeUpdate can be used for DDL

.github/release-please.yml, README.md
=> chore: update version numbers in README when releasing

samples/quickperf/pom.xml, samples/quickperf/src/main/java/com/google/cloud/jdbc/quickperf/QuickPerfRunner.java
Fixed transaction tagging and had to reset datafaker version in pom.xml
=> docs: fixed transaction tagging in quickperf app and reset datafaker version

README.md
=> docs: fix troubleshooting link

src/test/java/com/google/cloud/spanner/jdbc/MultiplexedSessionsTest.java
Add a couple of tests to verify that multiplexed sessions are being used by the JDBC driver when the environment variable has been set.
=> test: add tests for using multiplexed sessions

samples/spring-data-jdbc/googlesql/src/main/resources/application.properties, samples/spring-data-mybatis/googlesql/src/main/resources/application.properties
Repeatable read is currently in preview.
=> chore: use serializable as default isolation level
