googleapis/java-spanner-jdbc

src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java, src/test/java/com/google/cloud/spanner/jdbc/ConnectionOptionsTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
The project ID part of a connection URL should allow the use of dots and colons. This PR also replaces all usages of the deprecated class `org.junit.Assert` in the affected test classes with `com.google.common.truth.Truth`.
Fixes #33
=> fix: allow dots and colons in project id

pom.xml
The JDBC driver did not include the Spanner gRPC classes that are needed for testing.
Fixes #59
=> fix: include Spanner gRPC test dependencies

pom.xml
=> fix: add missing netty-shaded lib for über-jar

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcAbortedTransactionTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadOnlyTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadWriteAutocommitTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSimpleStatementsTest.java
Fixes deprecation warnings and moves to `com.google.common.truth.Truth` assertions for JDBC files.
=> fix: fix deprecation warnings in JDBC (test) files

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Adds documentation for properties that are supported for end users and that were missing from the list.
This change does not add documentation for the userAgent property, as it is not a property that should be set by end users. That property should only be set by libraries that are maintained by Google.
Fixes #152
=> fix: add missing documentation for connection properties

src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
The JDBC connection would return the current database name as the current catalog name, but that catalog name would not be returned in the ResultSet returned by getCatalogs(). This discrepancy causes some tools to ignore or misinterpret the catalog and schema structure of a Cloud Spanner database. Specifically, it breaks the autocomplete feature of DBeaver.
See also https://github.com/dbeaver/dbeaver/pull/9127
=> fix: return empty catalog name

pom.xml, src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java
The test failure was caused by the fact that the newer version of the Spanner client now uses the `ExecuteStreamingSql` RPC to execute PDML, as opposed to the `ExecuteSql` RPC in previous versions.
Fixes #183
=> chore(deps): update dependency com.google.cloud:libraries-bom to v8.1.0

pom.xml
@olavloite, @stephaniewang526, @elharo, @chingor13
As this repository uses the shared dependencies BOM now, google-cloud-spanner-bom has the dependencies necessary to replace the libraries-bom. It's more smaller and will not cause the dependency conflicts that are irrelevant to this repository (motivation: https://github.com/googleapis/java-spanner-jdbc/pull/251#issuecomment-721256007).
---
Fixes #252  ☕️
=> deps: use google-cloud-spanner-bom instead of libraries-bom

pom.xml
This build profile is no longer needed, as it has been moved to the client library together with the general Connection API.
=> chore: remove unused maven profile

README.md
Adds a simple code example for connecting to Cloud Spanner using JDBC.
Also fixes a wrong link to the online documentation.
=> docs: add simple connection sample to readme

src/main/java/com/google/cloud/spanner/jdbc/package-info.java
Adds a package-info.java file to the com.google.cloud.spanner.jdbc package, with a simple example for how to create a JDBC connection.
=> docs: add package-info to jdbc

pom.xml, samples/snippets/pom.xml
Closes #235 (which was for libraries-bom 12.0.0)
=> chore(deps): the libraries BOM 15.0.0

pom.xml
Removes the re-declaration of `grpc-google-cloud-spanner-...` as test dependencies as they are already transitive compile-time dependencies.
Fixes the failure in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/4278
=> deps: do not re-declare grpc dependencies as test dependencies

.readme-partials.yaml
Adds an example on how to create a connection to the README.
=> docs: add connection example to readme

clirr-ignored-differences.xml, src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
More methods from the Connection API should be exposed in the Cloud Spanner JDBC Connection interface to make it easier to execute read-only transactions with specific timestamp bounds.
This PR relies on [this PR in the client library](https://github.com/googleapis/java-spanner/pull/579) that is needed before this can be merged.
Towards #253
=> feat: expose more methods from Connection in JDBC

pom.xml
(Temporarily) fixes the dependency problem caused by the addition of `grpc-alts` as a runtime dependency in `google-cloud-spanner` and updates Spanner client library to 3.1.2.
Once https://github.com/googleapis/java-spanner/pull/757 has been merged and is available in the shared libraries, or another fix for the problem described in that PR, the TODO's in this PR can be reverted.
Replaces #293
=> deps: update spanner to 3.1.2

src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
If the client application would call `ResultSet#getMetaData()` more than once **before** calling `ResultSet#next()`, the `ResultSet` would skip a row when the rows would be consumed.
Fixes #322
=> fix: getting resultset metadata twice could skip row

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionGeneratedSqlScriptTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
Adds support for default `ClientInfo` properties. These are not required by the JDBC standard, but many applications (including IntelliJ) will try to set these, and will log a warning if they are not set. This will prevent that warning from being logged.
As a next step, these `ClientInfo` property values should be set as `SessionLabel` values in Cloud Spanner. This makes it possible to track which sessions are being used by which (JDBC) application.
=> feat: support default ClientInfo properties

.readme-partials.yaml, pom.xml
Some applications that load multiple JDBC drivers may run into dependency conflicts if other JDBC drivers use the same dependencies but different versions. This problem can be mitigated by creating a jar with shaded dependencies. This change adds a Maven profile for creating shaded jars.
Fixes #316
=> feat: support creating shaded jars

src/main/java/com/google/cloud/spanner/jdbc/JdbcArray.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcArrayTest.java
JDBC arrays have an optional method that allow them to be converted to `ResultSet`s. This method was not implemented for the Cloud Spanner JDBC driver. This would cause DBeaver to not be able to fetch and view the data of `NUMERIC` columns, as DBeaver would use this method for specifically those columns (other array columns would work). This PR fixes that specific problem and allows other users to use this convenience method for all array types.
Fixes #332
=> feat: Support Array conversion to ResultSet

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
One of the descriptions of the supported connection properties missed an ending `</code>` block, which caused the entire formatting to be incorrect.
Fixes #342
=> docs: fix javadoc formatting

src/main/java/com/google/cloud/spanner/jdbc/JdbcSqlExceptionFactory.java
Cloud Spanner JDBC Driver stack trace is not clear on cause of the issue when there is a DEADLINE_EXCEEDED error, making it more difficult for the customer and Cloud Support to debug the issue. This PR modifies the exception mapping to return the original exception rather than the message only, so that the entire stack trace is shown.
=> Fix: Return entire stack trace for deadline exceeded error

src/test/java/com/google/cloud/spanner/jdbc/JdbcTypeConverterTest.java
Re-enables a test that had been disabled because of an [issue](https://github.com/googleapis/java-core/pull/179) with pre-epoch Timestamps in java-core.
=> test: re-enable JDBC converter test

src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Enables the usage of UUIDs as a parameter in PreparedStatements. UUIDs are automatically translated to strings.
Fixes #364
=> feat: allow using UUID in PreparedStatement

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Calling `PreparedStatement#getMetaData()` actually executed the query or DML statement of the `PreparedStatement`. This PR changes that to only executing the statement in `PLAN` mode to get the metadata of the statement. That is:
1. More efficient, as the statement does not need to be executed.
2. Enables getting the metadata without first specifying a value for each parameter, as `PLAN` mode is allowed with unbound parameters.
This change also allows calling `PreparedStatement#getMetaData()` for DML statements. This will result in an empty `ResultSetMetaData` instance, as DML statements do not return any relevant information for a `ResultSetMetaData`.
Fixes #387
=> perf: use PLAN mode to get result metadata

.github/sync-repo-settings.yaml
Removes Java7 unit tests as a required check before a PR can be merged. This seems to be necessary before #397 can be merged.
=> build: remove java7 as required check

.github/sync-repo-settings.yaml, .github/workflows/ci.yaml, .kokoro/nightly/java7.cfg, .kokoro/presubmit/java7.cfg, pom.xml, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSet.java, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcWrapper.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcSqlExceptionFactory.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSetTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementWithMockedServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java
Upgrades the JDBC driver to Java 8 and implements new methods added in JDBC 4.2. JDBC version 4.2 is linked with Java 8.
Drops support for Java 7.
Fixes #396
=> feat!: upgrade to Java 8 and JDBC 4.2

.repo-metadata.json
This is used by autosynth to generate files such as the README.
=> chore: sets the min version of the repo as Java 8

.github/release-please.yml, .github/sync-repo-settings.yaml
Updates the github configuration to mark the branch 1.21.x as stable.
=> chore: marks the branch 1.21.x as stable

.github/release-please.yml, .github/sync-repo-settings.yaml, synth.py
Marks branch 1.21.x as stable.
Fixes sync-repo-settings.yaml file (removes duplicated line).
=> chore: marks branch 1.21.x as stable

src/main/java/com/google/cloud/spanner/jdbc/JdbcDataType.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcArrayTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSimpleStatementsTest.java
A `NullPointerException` was thrown if a `ResultSet` contained an array of `Struct`s and the `getArray()` method was called on the column.
Fixes #444
=> fix: NPE was thrown when getting an array of structs from a ResultSet

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcTypeConverter.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Adds support for getting a value from a `java.sql.ResultSet` as a `com.google.cloud.spanner.Value` instance, and for setting a parameter on a `java.sql.PreparedStatement` using a `com.google.cloud.spanner.Value` instance.
Fixes #452
=> feat: allow get/set Spanner Value instances

src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlScriptTest.java
In version 6.4.4 of spanner we have change the verifyStatementsInFile method to wrap any SQLExceptions into SpannerExceptions. In the failing tests we were catching SQLExceptions and ignoring them, since they were expected.
We have changed the tests to also ignore the respective SpannerExceptions.
=> tests: fixes sql script test

.readme-partials.yaml, src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Adds documentation for the supported connection properties to the README file.
Fixes #456
=> docs: document connection properties in README

pom.xml, src/test/java/com/google/cloud/spanner/jdbc/JdbcQueryOptionsTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcQueryOptionsTest.java
Updates to Spanner client 6.6.0 and adds tests for optimizer stats package.
Replaces #497
=> deps: update dependency com.google.cloud:google-cloud-spanner-bom to v6.6.0

pom.xml
Fixes #503 
In addition to original problem I have added an exception for all the Netty libraries since I have got errors on service provider which claims that netty libraries are not a subtype.
=> fix: prevent relocating urls that start with com like /computeMetadata/

.github/workflows/ci.yaml, .github/workflows/integration-tests-against-emulator.yaml, .github/workflows/samples.yaml
There is a bug with the maven-flattened plugin and maven 3.8.2, which is causing an error on builds. The yoshi team will file a bug under the plugin, but for now we need to downgrade maven to < 3.8.2.
=> chore: setup maven 3.8.1 for ci tasks

src/test/java/com/google/cloud/spanner/jdbc/ITAbstractJdbcTest.java
Removes the category from the base class for all integration tests so they are not excluded
from multiple builds, as the result is that both the category of the base class as well as
the concrete class are applied.
=> test: remove the category from the base class for all integration tests

pom.xml
Bumps the Mockito version used by the JDBC driver to 4.0, as the Spanner Java client has now also been updated.
Replaces #638 
cc @lesv
=> test(deps): update dependency org.mockito:mockito-core to v4

pom.xml
Some background: 
We want to run integration tests and unit tests (ending in *ClientTest) with the native profile. For this purpose, we want to [ignore any exclusions ](https://github.com/googleapis/java-shared-config/blob/ac44ba11d2da2f649670867c520f90253a8a41ff/pom.xml#L807) that take place in other maven-surefire-plugin configurations within the java-shared-config pom or other child poms so that we can explicitly include these tests. However, using `excludedGroups` in java-spanner-jdbc causes the **overriding of the exclusion** to be ignored. This results in integration tests being skipped in native mode which leads to native-image testing to fail with the message: ` Test configuration file wasn't found. Make sure that test execution wasn't skipped.`
This change replaces the use of …
=> fix(java): include integration tests for native image testing   

pom.xml, src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
Updates the Spanner client library dependency to 6.21.2 and fixes a test case that verified that a newline inside of a string literal would break the parser. This was however wrong, as PostgreSQL does allow string literals to contain unescaped newline characters.
Replaces #780
=> deps: update dependency com.google.cloud:google-cloud-spanner-bom to v6.21.2

src/test/java/com/google/cloud/spanner/jdbc/PgNumericPreparedStatementTest.java
The `PgNumericPreparedStatementTest` reset the entire mock server after each test, instead of only clearing the requests on the mock server. This would also clear all sessions on the mock server, which could cause a `Session not found` error to occur occasionally.
Fixes #754
=> test: fixed test case that reset entire mock server instead of only requests

src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPgDatabaseMetaDataTest.java
Adds `pg_catalog` as an expected schema to the JDBC metadata tests.
Fixes #810
=> test: add pg_catalog as an expected schema

pom.xml, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTimeoutTest.java
The `Statement#executeBatch()` method did not respect the statement timeout that had been set on a statement. This meant that a batch like the following would always use the default timeout that is set in the Gapic generated client, and ignore the timeout set in `Statement#setTimeout(int)`:
```java
statement.setQueryTimeout(120);
statement.addBatch("insert into foo (id) values (1)");
statement.executeBatch(); // This ignored the statement timeout
```
Fixes #870
=> fix: executeBatch did not respect statement timeout

src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
Some tests used invalid escaping of quotes in PostgreSQL queries. They
assumed that a quote in a quoted string could be escaped by prefixing
it with a backslash. This is however not allowed in PostgreSQL, and
instead the quote must be escaped by including the same quote twice in
the string.
The Spanner Java client library contained a bug that allowed the
backslash-escaped quotes to be accepted. This bug has been fixed in
6.25.7 and these tests therefore need to be modified to be able to
update to that version.
Fixes the build error in #898
=> test: modify tests to use correct quote escaping

.kokoro/build.sh, pom.xml
This PR temporarily introduces a native image compilation profile which fixes the version of the native-maven-plugin to 0.9.11. This is to unblock the shared-config dependency from being upgraded.
=> ci: temporarily using native-maven-plugin 0.9.11 for testing

src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
Types.BOOLEAN and Types.BIT should have identical behaviour for nullability. In master, BOOLEAN is nullable but BIT will throw IllegalArgumentException if an attempt is made to set a null value.
Fixes https://github.com/googleapis/java-spanner-jdbc/issues/919
=> fix: Types.BOOLEAN and Types.BIT should have identical behaviour for nullability

.kokoro/build.sh, pom.xml
Upgrading to GraalVM 22.2 requires a minimum of 0.9.13 of the native-maven-plugin. However, 0.9.13 contains an issue that breaks java-spanner-jdbc's build. TODO: Remove this upgrade once java-shared-config 1.5.4 (with the [native-maven-plugin upgrade to 0.9.14](https://github.com/googleapis/java-shared-config/pull/515)) is released.
=> fix: upgrade native image plugin to 0.9.14 to unblock graalvm 22.2 update

pom.xml, src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-spanner-jdbc/native-image.properties
```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of com.google.cloud.spanner.Dialect$1 are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=com.google.cloud.spanner.Dialect$1.
at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:140)
at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:583)
at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
at …
```
=> fix(java): initialize classes at build-time to address native image 22.2.0 issues

.kokoro/nightly/integration.cfg
The pom.xml file has reference to `gcloud-devel` project, but the nightly integration kokoro configuration has reference to `java-docs-samples`. This PR sets the project to `gcloud-devel` at both places.
Fixes #820
=> chore: correct spanner project reference for ITs

pom.xml
This PR reverts scope change of `gax` dependency in https://github.com/googleapis/java-spanner-jdbc/pull/918/files.
We now set the scope to `runtime`.
Fixes #1034
=> chore: edit scope of gax dep from test to runtime

clirr-ignored-differences.xml, pom.xml, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcSavepoint.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcSavepointTest.java, src/test/java/com/google/cloud/spanner/jdbc/SavepointMockServerTest.java
Add support for emulated Savepoints that are now supported in the client library.
=> feat: support Savepoint

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementWithMockedServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDatabaseMetaDataTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPgDatabaseMetaDataTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java, src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables.sql, src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables_Emulator.sql, src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables_PG.sql
Support untyped null parameter values for `PreparedStatement`. This will allow users to add null values as a statement parameter value without having to know what type the column that the parameter is bound to uses.
=> feat: support untyped NULL value parameters

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/ExecuteMockServerTest.java
Refactor the execute methods a bit so they all share the same do-with-timeout logic.
=> chore: share do-with-timeout code

src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
Adds a method for creating a JDBC ResultSet that creates a copy of a Cloud Spanner ResultSet. This type of ResultSet can be used for small result sets that are unlikely to be closed by the client application, such as a ResultSet that holds the generated keys of an update statement. If an application requests the JDBC driver to return the generated keys, and then never gets and closes the generated keys ResultSet, the underlying session and/or result stream could be leaked.
=> chore: add copyOf method for result sets

pom.xml, src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/ExecuteMockServerTest.java
Close the underlying ResultSet if the result that was returned for an
executeUpdate call turned out to be of an unexpected type.
=> fix: session leak for invalid update

.github/workflows/spring-data-mybatis-sample.yaml, samples/spring-data-jdbc/pom.xml, samples/spring-data-mybatis/pom.xml
- Removes the specific JDBC version from the samples. This is no longer needed, as the BOM now contains a JDBC driver version that is up-to-date enough to work with these samples (they require RETURN_GENERATED_KEYS).
- Adds a GitHub Actions workflow for testing the MyBatis sample.
=> deps: remove specific JDBC version from samples

pom.xml
The maven-javadoc-plugin version is defined in the shared config pom.xml.
https://github.com/googleapis/java-shared-config/blob/778a547a09de71dbf9e5a42b155f12d15c319864/pom.xml#L472
The removal of the 4 lines corresponds to the lines touched by the recent RenovateBot:
https://github.com/googleapis/java-spanner-jdbc/pull/1349
Parent issue: https://github.com/googleapis/java-shared-config/issues/673
=> build: do not declare javadoc plugin version

src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDatabaseMetaDataTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPgDatabaseMetaDataTest.java
The JDBC driver would return the empty string as the current catalog and schema for PostgreSQL databases. This is incorrect, as the default catalog and schema for PostgreSQL is the database name and the 'public' schema.
=> feat: support default schema and catalog for PostgreSQL databases

src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
Cloud Spanner JDBC connections do not maintain a physical connection to Cloud Spanner, but are merely a wrapper around the underlying Java client library. This again uses a pool of gRPC channels to communicate with Cloud Spanner. This means that a single JDBC connection will never lose its network connection with Cloud Spanner, and checking whether it is valid or not by executing a query every time is not useful. Instead, the check should:
1. Verify that a connection has successfully been established with Cloud Spanner. The result should be cached for all JDBC connections using the same Cloud Spanner client library instance.
2. Verify that the connection has not been closed.
The above can be achieved by checking that the dialect of the database that the connection is connected to has been …
=> perf: optimize isValid implementation

pom.xml, src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java, src/test/java/com/google/cloud/spanner/jdbc/PartitionedQueryMockServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/PgNumericResultSetTest.java
Updates the Spanner client to 6.57.0 and modifies some test cases to work with the newest version of the Spanner client. The manual changes other than the dependency update are:
1. The Spanner client now supports PROTO and PROTO ENUM columns. This is also reflected in the RandomResultSetGenerator, which means that the number of columns is increased from 18 to 22.
2. The above addition of PROTO and PROTO ENUM means that the error message changes when you try to get a blob with a wrong column.
3. The newly introduced statement cache must be disabled, as there is a small bug that prevents the first query to include any default query options (e.g. optimizer version).
=> deps: update dependency com.google.cloud:google-cloud-spanner-bom to v6.57.0

src/test/java/com/google/cloud/spanner/jdbc/SavepointMockServerTest.java
Only change the dialect result that is returned by the mock server when the dialect has actually changed. This makes the test a bit quicker, as we also don't have to close the SpannerPool after each test.
=> chore: only reset dialect result when it has changed

src/test/java/com/google/cloud/spanner/jdbc/TransactionMockServerTest.java
Adds a couple of tests to verify that empty transactions are translated to no operations on Cloud Spanner.
=> test: add tests to verify behavior of empty transactions

.kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg, owlbot.py, pom.xml
Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central in https://github.com/googleapis/java-spanner-jdbc/pull/1480
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290
=> chore: use sdk-platform-java-config to consolidate build configs

src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/ExecuteMockServerTest.java
Verifies that client-side statements can now also be executed using the executeQuery and executeUpdate methods.
Replaces #1152
=> test: verify execution of client side statements

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcWrapper.java
Remove the custom type name implementation in the JDBC driver and rely on the implementation in the Java client library.
=> chore: remove custom type name implementation

pom.xml
Follow-up to https://github.com/googleapis/java-spanner-jdbc/pull/1486. These changes were overridden by release-please in https://github.com/googleapis/java-spanner-jdbc/pull/1484 
Thanks for catching this @alicejli!
=> chore: restore sdk-platform-java-config changes.

src/main/java/com/google/cloud/spanner/connection/ConnectionHelper.java, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java
Add a connection helper to get the underlying Spanner instance. This helper will be removed once the getSpanner() method has been made public in the Java client library.
=> chore: add connection helper to get Spanner instance

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/StatementResourcesTest.java
Release the underlying resources of any ResultSet when Statement#close()
is called. This is necessary in case someone executes a query in
auto-commit mode using Statement#execute(String), and never reads and/or
closes the result that was returned.
=> fix: release ResultSet on Statement#close() 

pom.xml, src/test/java/com/google/cloud/spanner/jdbc/ConcurrentTransactionOnEmulatorTest.java
The JDBC driver now supports running multiple concurrent transactions on the emulator using a single thread. The emulator still only supports one read/write transaction per database at any time, but the JDBC driver works around this by manually setting a Savepoint after each statement, and using that Savepoint to automatically resume the transaction when it has been aborted by the emulator.
=> feat: concurrent transactions on emulator

src/test/java/com/google/cloud/spanner/jdbc/ClientSideStatementHintsTest.java, src/test/java/com/google/cloud/spanner/jdbc/TagMockServerTest.java
The JDBC driver now supports setting statement tags and RPC priority as a statement hint.
Usage:
* `@{STATEMENT_TAG='my-tag'} SELECT 1;` (GoogleSQL)
* `/*@STATEMENT_TAG='my-tag'*/ SELECT 1;` (PostgreSQL)
Also, RPC priority can be set using a statement hint:
* `@{RPC_PRIORITY=PRIORITY_LOW} SELECT 1;` (GoogleSQL)
* `/*@RPC_PRIORITY=PRIORITY_LOW*/ SELECT 1;` (PostgreSQL)
=> feat: support statement tags in hints

.github/workflows/auto-release.yaml
Stop auto-merging releases, even if they only contain dependency updates, as it causes a too large number of releases to go out.
=> build: stop auto merging releases

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Added support for an 'endpoint' connection URL property. This property can be added to either the Connection URL or the Properties object that is used to create a Connection, and can be used in combination with the autoConfigEmulator connection property to connect to an emulator instance that uses a randomly assigned port number.
See https://github.com/googleapis/java-spanner-jdbc/blob/main/src/test/java/com/google/cloud/spanner/jdbc/ConcurrentTransactionOnEmulatorTest.java for an example on how to use this property.
=> feat: support endpoint connection URL property

src/test/java/com/google/cloud/spanner/jdbc/DdlMockServerTest.java
Adds support for running DDL statements when a connection is in autocommit=false mode. By default, DDL statements are only allowed when no transaction is active. That is; no query or DML statement has been executed which activated a read/write transaction.
A new flag is added that can be used to revert the behavior back to the original behavior where DDL is always refused when autocommit=false. The same flag can also be used to make the API behave the same as MySQL and Oracle, where any active transaction is automatically committed whenever a DDL statement is encountered.
Concretely this means that the following is now allowed:
```
set autocommit=false;
create table Singers (SingerId INT64, Name STRING(MAX)) PRIMARY KEY (SingerId);
```
The following is by default NOT allowed, unless …
=> feat: allow DDL with autocommit=false

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Documents the support for overlapping transactions on the emulator in the Connection API, even when these are executed on one thread. This is normally not supported, as it requires multiple transactions to run concurrently on the emulator.
This change works around that by keeping track of what the active transaction on the emulator is, and then abort that transaction when another transaction needs to make progress. The transaction that was aborted will be retried up to the point where it was when it again wants to make progress.
This step-by-step progress is implemented by automatically setting a savepoint in the transaction after each successful step. The transaction is then rolled back to that savepoint when another transaction needs to make progress.
The feature is only enabled if the …
=> docs: support concurrent transactions on the emulator

pom.xml
Remove the open-telemetry dependency import, as it is already defined in the shared dependencies.
=> deps: remove open-telemetry dependency import

src/main/java/com/google/cloud/spanner/SessionPoolOptionsHelper.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java, src/test/java/com/google/cloud/spanner/MockServerHelper.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionUrlTest.java, src/test/java/com/google/cloud/spanner/jdbc/MultiplexedSessionsMockServerTest.java
Enable the use of multiplexed sessions by default for queries in auto-commit mode. Multiplexed sessions can handle any number of queries concurrently. This means that the JDBC driver does not need to check out a session exclusively from the internal session pool in order to execute a query. Instead, a single multiplexed session is enough for all queries that are executed by all JDBC connections that connect to the same Spanner database. This allows a higher degree of parallelism to be achieved from a single client machine.
Note that due to how the JDBC API is defined, each JDBC connection can only execute one query at a time. If you for example want to execute 1000 queries in parallel, then you also need to create 1000 JDBC connections. Spanner JDBC connection are however lightweight, as …
=> perf: use multiplexed sessions

src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
Updates the results that we return for methods that relate to named schemas in `DatabaseMetaData`,  as Spanner now supports named schemas.
=> feat: update DatabaseMetaData to include named schemas

.github/sync-repo-settings.yaml
In this PR:
- Remove Owlbot postprocessor as a required check.
=> chore: remove owlbot check

samples/spring-data-jdbc/src/main/java/com/google/cloud/spanner/sample/JdbcConfiguration.java, samples/spring-data-jdbc/src/test/java/com/google/cloud/spanner/sample/ApplicationTest.java
Simplify the dialect detection for the Spring Data JDBC sample to use the built-in function for getting the dialect of a Spanner database.
=> docs: simplify dialect detection in Spring Data JDBC sample

src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
Cleans up a small TODO in the JDBC driver for getting the default schema based on the database dialect.
=> chore: use default schema from Dialect

src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITOpenTelemetryTest.java
The OpenTelemetry metrics that were gathered by the JDBC driver also included a unique Connection ID for each connection. This creates too many time series.
=> fix: remove connection-id from metrics

README.md, src/test/java/com/google/cloud/spanner/jdbc/ExecuteMockServerTest.java
The `auto_batch_dml` connection property enables automatic batching of DML statements, for example when using Hibernate. When this connection variable has been enabled, a JDBC connection will automatically buffer DML statements in memory, and send all buffered DML statements to Spanner as one batch when a query is executed or when the transaction is committed. This can significantly reduce the number of round-trips to Spanner, especially when using an ORM like Hibernate that generates many small single-row DML statements.
=> feat: auto_batch_dml connection property

clirr-ignored-differences.xml, src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/AutoBatchDmlMockServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSimpleStatementsTest.java
Adds methods for enabling/disabling auto_batch_dml.
Also enables the use of this feature in combination with other JDBC batches. This again allows PreparedStatement#addBatch() and Statement#addBatch(String) to be used in combination with auto_batch_dml. This again makes it usable in combination with frameworks like Hibernate.
=> feat: auto_batch_dml methods + combination with JDBC batching

samples/spring-data-jdbc/pom.xml, samples/spring-data-jdbc/src/main/java/com/google/cloud/spanner/sample/OpenTelemetryConfiguration.java
Add a metrics exporter to the sample application to show how to export both traces and metrics when using the JDBC driver.
=> docs: add metrics exporter to sample app

README.md, src/test/java/com/google/cloud/spanner/jdbc/FallbackToPartitionedDMLMockServerTest.java
DML statements that are executed in auto-commit mode can use either atomic transactions, or partitioned non-atomic transactions. The former is bound by the mutation limits in Spanner. The latter may update/delete any number of rows.
The transaction type that is used to execute DML statements in auto-commit mode is determined by the connection variable `autocommit_dml_mode`. This connection variable now supports a third value. The supported values are:
- TRANSACTIONAL (default): Uses atomic read/write transactions.
- PARTITIONED_NON_ATOMIC: Use Partitioned DML for DML statements in auto-commit mode. Use this mode to execute DML statements that exceed the transaction mutation limit in Spanner.
- TRANSACTIONAL_WITH_FALLBACK_TO_PARTITIONED_NON_ATOMIC: Execute DML statements using atomic …
=> feat: add fallback to PDML mode

pom.xml, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTimeoutTest.java
Store the query timeout internally as a java.time.Duration, so we can use a smaller unit for testing. This again allows us to enable the timeout tests by default.
=> chore: store query timeout as a java.time.Duration

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTimeoutTest.java
Clear the interrupted flag after cancelling a statement when using a direct executor.
Fixes #1879
=> fix: clear interrupted flag after cancel

src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
Fixes #<issue_number_goes_here> ☕️
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
=> feat: support for spanner external host

clirr-ignored-differences.xml, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java, src/test/java/com/google/cloud/spanner/jdbc/DdlMockServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
Adds methods for unwrapping the underlying DatabaseClient and Spanner instance that is used by a JDBC connection.
=> feat: add methods for unwrapping Spanner client

src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
Spanner now supports FOR UPDATE clauses. This is now also reflected in the DatabaseMetaData returned by the JDBC driver.
See also https://cloud.google.com/spanner/docs/release-notes#January_27_2025
=> feat: support FOR UPDATE clauses

src/test/java/com/google/cloud/spanner/jdbc/ExecuteMockServerTest.java
Statements that are executed in autocommit mode should use the last_statement optimization. This reduces the number of validations that Spanner executes after executing the statement, which again reduces the overall execution time of DML statements that are executed in autocommit mode.
=> perf: use last_statement optimization in autocommit

src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/IsolationLevelConverter.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java, src/test/java/com/google/cloud/spanner/jdbc/IsolationLevelConverterTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java, src/test/java/com/google/cloud/spanner/jdbc/TransactionMockServerTest.java
Adds support for setting the transaction isolation level to repeatable read.
=> feat: support isolation level repeatable read

.github/workflows/ci.yaml, .kokoro/build.sh, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcResultSet.java, src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java, src/main/java/com/google/cloud/spanner/jdbc/IsolationLevelConverter.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcConstants.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDataSource.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcSqlException.java, src/main/java/com/google/cloud/spanner/jdbc/JsonType.java, src/main/java/com/google/cloud/spanner/jdbc/PgJsonbType.java, src/main/java/com/google/cloud/spanner/jdbc/ProtoEnumType.java, src/main/java/com/google/cloud/spanner/jdbc/ProtoMessageType.java, src/main/java/com/google/cloud/spanner/jdbc/SpannerPool.java, src/main/java/com/google/cloud/spanner/jdbc/UuidType.java, src/test/java/com/google/cloud/spanner/jdbc/DdlMockServerTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcSqlScriptVerifier.java, src/test/java/com/google/cloud/spanner/jdbc/it/SingerProto.java
Follows from googleapis/java-shared-config#1003
=> chore: update linter groupd ID to the latest

.kokoro/build.sh, .kokoro/presubmit/integration.cfg, src/test/java/com/google/cloud/spanner/jdbc/it/ITOpenTelemetryTest.java
Use the default environment for integration tests.
Also adds an explicit check to the test whether there are credentials available to make debugging Unauthenticated errors in integration tests a bit easier.
=> build: use the default env for integration tests

README.md
The JDBC driver now uses a single multiplexed session for all operations. This applies to all operations in auto-commit mode, in read-only transactions, and in read/write transactions.
One multiplexed session can execute an unlimited number of operations concurrently.
Configuring minSessions and maxSessions in the connection URL is therefore no longer needed for workloads that execute a large number of concurrent transactions.
=> feat: a single multiplexed session is used for all operations

src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java, src/main/java/com/google/cloud/spanner/jdbc/JdbcSimpleParameterMetaData.java, src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java, src/test/java/com/google/cloud/spanner/jdbc/PreparedStatementParameterMetadataTest.java
Add an option to use simple PreparedStatement ParameterMetadata that only uses client-side information. This prevents round-trips to Spanner when calling the method PreparedStatement#getParameterMetaData(), for example when these are triggered by frameworks like Spring Data.
This option is experimental and could be removed in future releases.
The option can be enabled by setting the system property `spanner.jdbc.use_simple_parameter_metadata=true`
=> chore: support simple statement param metadata

samples/spring-data-mybatis/googlesql/pom.xml
Adds the ByteBuddy dependency that is needed for some test workarounds for mTLS.
=> chore: add ByteBuddy for tests for MyBatis sample
